### PR TITLE
Add ReactiveUI Logo

### PR DESCRIPTION
**Pull request by worldbeater**
✨ @ghuntley come check `#reactiveui-docs` channel at Slack! ✨

image

### CODE REVIEW

**Comment by RLittlesII** [comment]
@worldbeater I know you provided the psd files.  Would it be too much to ask for these in svg format?

**Comment by glennawatson** [comment]
Or both I guess

**Comment by worldbeater** [comment]
Working on it. Stay tuned 👍

**Review by glennawatson — APPROVED** [review]

**Review by glennawatson — APPROVED** [review]

**Comment by worldbeater** [comment]
Done!

**Review by RLittlesII — APPROVED** [review]

**Pull request merged**
